# Generated by Django 5.0.1 on 2025-11-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_newslettercampaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettercampaign',
            name='plain_text_content',
        ),
        migrations.AlterField(
            model_name='newslettercampaign',
            name='content',
            field=models.TextField(help_text='Newsletter content - you can use simple HTML tags like <h1>, <p>, <ul>, <li>, <a>, <strong>, etc.'),
        ),
    ]
